export const classes = {
  chatBotHelper: {
    display: 'flex',
    justifyContent: 'flex-end',
    position: 'fixed',
    width: '100%',
    marginLeft: '-20px',
    marginTop: '100px',
    zIndex: '1',
  },
  containerCoponent: {
    padding: '8px',
    lineHeight: '1.9',
    fontWeight: 'bold',
    fontSize: '1.2rem',
    textAlign: 'center',
  },
  chatButton: {
    backgroundColor: '#610527',
    border: '1px solid #ccc',
    borderRadius: '50%',
    height: '50px',
    width: '30px',
    color: '#fff',
    margin: '10px',
    cursor: 'pointer',
    marginTop: '600px',
    position: 'fixed',
    right: '0',
    bottom: '0',
    fontSize: '2rem',
    zIndex: '1',
    '&:hover': {
      backgroundColor: '#610527',
    },
  },
};
