export const classes = {
  chatBotHelper: {
    display: 'flex',
    justifyContent: 'flex-end',
    position: 'fixed',
    width: '100%',
    marginLeft: '-20px',
    marginTop: '17.5rem',
    zIndex: '1',
  },
  containerCoponent: {
    padding: '8px',
    lineHeight: '1.9',
    fontWeight: 'bold',
    fontSize: '1.2rem',
    textAlign: 'center',
    cursor: 'pointer',
  },
  chatButton: {
    backgroundColor: '#000',
    border: '1px solid #ccc',
    borderRadius: '50%',
    height: '50px',
    width: '30px',
    color: '#fff',
    margin: '10px',
    cursor: 'pointer',
    marginTop: '600px',
    position: 'fixed',
    right: '0',
    bottom: '0',
    fontSize: '2rem',

    zIndex: '1',
    '&:hover': {
      backgroundColor: '#610527',
    },
  },
  tikcetInfo: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '10px',
    marginBottom: '15px',
    borderBottom: '1px solid #ccc',
    fontSize: '0.9rem',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  programInfo: {
    marginTop: '10px',
    marginBottom: '15px',
    borderBottom: '1px solid #ccc',
    borderTop: '1px solid #ccc',
    fontSize: '1.1rem',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
};
